version: '3'
services:
  db:
    image: mysql:5.7
    container_name: 'virtual_currency_mysql'
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3316:3306'
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql

  app:
    build: .
    command: bundle exec rails s
    container_name: 'virtual_currency_app'
    volumes:
      - .:/var/www/virtual_currency/
    ports:
      - "3000:3000"
    links:
      - db

  nginx:
    image: nginx:latest
    container_name: 'virtual_currency_nginx'
    ports:
      - "80:80"
    volumes:
      - ./development.nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/virtual_currency
    links:
      - app
